deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -a --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='.well-known' ./ $DEPLOYPATH
